var companyNames = [
	"CompanyName",
	"Xoriant Corporation",
	"Inmata Solutions, Inc.",
	"InfoLlact, LLC",
	"Etouch Systems Corp",
	"Virtue Group",
	"Online Technical Services",
	"KirkSearch",
	"Softsol Resources Inc",
	"Ness Software Engineering Services",
	"SUPERMICRO COMPUTER INC",
	"IPS",
	"University of California - San Francisco",
	"Intuitive Surgical, Inc.",
	"Verizon",
	"HP",
	"Nelson Technology",
	"WinMax Systems Corporation",
	"US Court of Appeals",
	"iD Tech",
	"Skyrocket Ventures",
	"Rootshell Enterprise Technologies Inc.",
	"NetPace",
	"Elti Solutions",
	"Reputation.com, Inc.",
	"Groupon",
	"F5 Networks, Inc.",
	"Provide Commerce",
	"ExactTarget",
	"GATE Staffing",
	"Xoriant Corporation",
	"TRIAD Group",
	"Magagnini Network, LLC",
	"Task Management Inc",
	"Intelliswift Software Inc",
	"M-C Recruitment",
	"Sherpa",
	"GDI Infotech, Inc.",
	"Banyan Air Service",
	"Marsh Consulting Services",
	"Advantex Professional Services",
	"Samiti Technology Inc.",
	"The Bowdoin Group",
	"SunTechPros, Inc.",
	"Zion Partners",
	"HT Staffing Professional, LLC",
	"Data Incorporated",
	"Ascent",
	"Technosoft Engineering",
	"Santa Cruz Biotechnology, Inc.",
	"Online Technical Services",
	"Engage Partners",
	"Global Infotech Corporation",
	"Combined Computer Resources",
	"The Bowdoin Group",
	"Trinamix",
	"Trade Street Consulting",
	"TECHstaff Resources, Inc.",
	"True Source IT, LLC",
	"IDC Technologies",
	"Themesoft Inc",
	"Yochana IT Solutions",
	"SMCI",
	"MindWorld LLC",
	"K Anand Corporation",
	"HT Solutions",
	"Spruce Technology Inc.",
	"Adept Solutions Inc",
	"Salestream Software",
	"TECHSOL4U, Inc.",
	"Red Zone Resources",
	"Resource IT Group",
	"TeamSoft",
	"Sapvix",
	"Bhrigus",
	"Skyrocket Ventures",
	"ATMECS",
	"HT Solutions",
	"Walter Bacon",
	"Galax-Esystems Corp",
	"Databerry Inc",
	"Palni Inc",
	"Case Interactive",
	"Softcrylic",
	"Elevate Recruiting Group",
	"Red River Solutions",
	"Everest Solutions Group",
	"Technical Integrity",
	"Bachrach Group, Ltd",
	"Technology Navigators",
	"Amerit Consulting",
	"Intellect Technical Solutions, Inc.",
	"ICore Infotech",
	"Vertex Solutions Inc.",
	"Seek Infotech LLC",
	"Best IT Experts",
	"Mainz Brady Group",
	"Mindlance",
	"Vaco - Nashville",
	"Crossfire Consulting Corp",
	"Trade Street Consulting",
	"Waltech, Inc.",
	"CORESTAFF Technology Group",
	"Adboom Group",
	"Ariston Tek, Inc.",
	"Vaco - San Diego",
	"Vaco - Orlando",
	"QSOLV, INC.",
	"Brooksource",
	"Sabriel Corporation",
	"NGP",
	"Akraya Inc.",
	"International Information Technology Team, Inc.",
	"CareerEncore, Inc",
];